config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'transactions/index'
  # get 'transactions/show'
  # get 'accounts/index'
  # get 'accounts/show'
  resources :connections, only: %i[index new show] do
    resources :accounts, only: %i[index show] do
      resources :transactions, only: %i[index show]
    end
  end
  get '/create_customer', to: 'salt_edge#create_customer'
  # get '/create_connection', to: 'salt_edge#create_connection'
  # get 'salt_edge/connections'
  # get 'salt_edge/accounts'
  # get 'salt_edge/transactions'
  devise_for :users
  root to: 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

require 'account'

class AccountsController < ApplicationController
  def index
    @connection_id = params['connection_id']
    url = "https://www.saltedge.com/api/v5/accounts?connection_id=#{@connection_id}"
    api = Saltedge.new(APP_ID, SECRET, 'private.pem')
    response = api.request(:get, url)
    @accounts = response['data'].map { |hash| Account.new(hash) }
  end

  def show
    @connection_id = params[:connection_id]
    account_id = params[:id]
    url = "https://www.saltedge.com/api/v5/accounts?connection_id=#{@connection_id}"
    api = Saltedge.new(APP_ID, SECRET, 'private.pem')
    response = api.request(:get, url)
    response['data'].each do |account|
      @account = account if account['id'] == account_id
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/connections_controller.rb
# frozen_string_literal: true

require 'connection_object'
require 'saltedge'

class ConnectionsController < ApplicationController
  def index
    customer_id = current_user.customer_id
    url = "https://www.saltedge.com/api/v5/connections?customer_id=#{customer_id}"
    api = Saltedge.new(APP_ID, SECRET, 'private.pem')
    response = api.request(:get, url)
    @connections = response['data'].map { |hash| ConnectionObject.init(hash) }
  end

  def show
    connection_id = params[:id]
    url = "https://www.saltedge.com/api/v5/connections/#{connection_id}"
    api = Saltedge.new(APP_ID, SECRET, 'private.pem')
    response = api.request(:get, url)
    @connection = response['data']
  end

  def new
    customer_id = current_user.customer_id
    param = {
      'data' => {
        'customer_id' => customer_id,
        'consent' => {
          'scopes' => %w[
            account_details
            transactions_details
          ],
          'from_date' => Time.new.to_date.to_s
        },
        'attempt' => {
          'return_to' => 'http://127.0.0.1:3000/connections'
        }
      }
    }
    url = 'https://www.saltedge.com/api/v5/connect_sessions/create'
    api = Saltedge.new(APP_ID, SECRET, 'private.pem')
    response = api.request(:post, url, param)
    redirect_to response['data']['connect_url']
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/salt_edge_controller.rb
# frozen_string_literal: true

class SaltEdgeController < ApplicationController
  def create_customer
    identifier = current_user.email
    url = 'https://www.saltedge.com/api/v5/customers'
    param = { 'data' => { 'identifier' => identifier } }
    api = Saltedge.new(APP_ID, SECRET, 'private.pem')
    response = api.request(:post, url, param)
    current_user.update(customer_id: response['data']['id'])
    pp current_user.customer_id
    pp 'HERE'
    redirect_to root_path
  end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

require 'transaction'

class TransactionsController < ApplicationController
  def index
    @connection_id = params['connection_id']
    @account_id = params['account_id']
    url = "https://www.saltedge.com/api/v5/transactions?connection_id=#{@connection_id}&account_id=#{@account_id}"
    api = Saltedge.new(APP_ID, SECRET, 'private.pem')
    response = api.request(:get, url)
    @transactions = response['data'].map { |hash| Transaction.new(hash) }
  end

  def show
    @connection_id = params['connection_id']
    @account_id = params['acount_id']
    transaction_id = params['id']
    url = "https://www.saltedge.com/api/v5/transactions?connection_id=#{@connection_id}&account_id=#{@account_id}"
    api = Saltedge.new(APP_ID, SECRET, 'private.pem')
    response = api.request(:get, url)
    response['data'].each do |transaction|
      @transaction = transaction if transaction['id'] == transaction_id
    end
  end
end

app/helpers/accounts_helper.rb
# frozen_string_literal: true

module AccountsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def log_in(classa: '')
    if current_user
      link_to 'Log Out', destroy_user_session_path, 'data-method': :delete, class: classa
    else
      link_to 'Sing In', new_user_session_path, class: classa
    end
  end

  def connected(classa: '')
    if current_user&.customer_id
      link_to 'Dasbord', connections_path, class: classa
    else
      link_to 'Connect Customer Account', create_customer_path, class: classa
    end
  end
end

app/helpers/connections_helper.rb
# frozen_string_literal: true

module ConnectionsHelper
  def check_customer_id
    return True if current_user&.customer_id
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/salt_edge_helper.rb
# frozen_string_literal: true

module SaltEdgeHelper
end

app/helpers/transactions_helper.rb
# frozen_string_literal: true

module TransactionsHelper
end

app/views/accounts/index.html.erb
<h1>Accounts</h1>

<table class="table table-hover">

  <thead>
    <tr>
      <th>account id</th>
      <th>Name</th>
      <th>Nature</th>
      <th>balance</th>
      <th>currency</th>
      <th>transactions</th>
      <th>details</th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do | account | %>
    <tr>
      <td><%= account.id %></td>
      <td><%= account.name %></td>
      <td><%= account.nature %></td>
      <td><%= account.balance %></td>
      <td><%= account.currency_code %></td>
      <td><%= link_to 'list', connection_account_transactions_path(@connection_id, account.id) %></td>
      <td><%= link_to "more", connection_account_path(@connection_id,account.id)%> </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/accounts/show.html.erb
<div class="container">
  <%=  link_to " ⬅ back ", connection_accounts_path, class:"btn btn-primary" %> <br><br>
<% @account.each_pair do |key, value| %>
  
  <strong> <%= key.to_s %> </strong> <br>
  <%= value %>
  <br><br>
<% end %>
  </div>  

app/views/connections/index.html.erb
<div class="page-header">
  <h1>Connections</h1>
</div>
<%= if @connections.empty? then "There is no connections" end %>
<br>
<table class="table table-hover">

  <thead class=""> 
    <tr>
      <td>id</td>
      <td>customer_id</td>
      <td>provider_name</td>
      <td>status</td>
      <td>accounts</td>
      <td>more info</td>
    </tr>
  </thead>

  <tbody>
    <% @connections.each do |connection| %>
      <tr>
        <td>  <%= connection.id %> </td>
        <td> <%= connection.customer_id %> </td>
        <td> <%= connection.provider_name %></td>
        <td> <%= connection.status %></td>
        <td> <%= link_to "link", connection_accounts_path(connection.id) %></td>
        <td> <%= link_to "more", connection_path(connection.id) %> </td>
      </tr>
    <% end %>
  </tbody>

</table>
<%= link_to "add connection", new_connection_path, class:"btn btn-info" %>

app/views/connections/new.html.erb
wait a second

app/views/connections/show.html.erb
<div class="container">
  <%=  link_to " ⬅ back ", connections_path, class:"btn btn-primary" %> <br><br>
<% @connection.each_pair do |key, value| %>
  
  <strong> <%= key.to_s %> </strong> <br>
  <%= value %>
  <br><br>
<% end %>
  </div>  

app/views/home/index.html.erb
<h3>HOME</h3>

<% if current_user %>
<p>
  <% if  current_user.customer_id%>
    <%= link_to "Dashbord", connections_path, class:"btn btn-primary" %>
  <% else %>
    <p> You don't have a connected SaltEdge customer account 
    create one by following this <%= link_to 'link', create_customer_path %>.
    </p>
  <% end %>
</p>
<% end %>
<%= log_in classa:"btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTestTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="">
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <div class="navbar-item">
          <%= link_to "RailsTestTask", root_path, class: "nav-link text-white" %>
        </div>
        <ul class="nav">
          <li> <%= connected classa: 'nav-link text-white' %> </li>
          <li> <%= log_in classa: 'nav-link text-white' %> </li>
        </ul>
      </div>
    </nav>
    <div class="row">
      <div class="column justify-midle">
        <%= yield %>
      </div>
    </div>
    <div class="position-absolute top-100 start-50 translate-middle">
      <%= notice %>
    </div>

    <div class="position-absolute top-100 start-50 translate-middle">
      <%= alert %>
    </div>
    
  </body>
</html>

app/views/salt_edge/accounts.html.erb
<h1>SaltEdge#accounts</h1>
<p>Find me in app/views/salt_edge/accounts.html.erb</p>

app/views/salt_edge/connections.html.erb
<h1>SaltEdge#connections</h1>
<p>Find me in app/views/salt_edge/connections.html.erb</p>

app/views/salt_edge/transactions.html.erb
<h1>SaltEdge#transactions</h1>
<p>Find me in app/views/salt_edge/transactions.html.erb</p>

app/views/transactions/index.html.erb
<h1>Transactions</h1>

<table class="table table-hover"> 

  <thead>
    <tr>
      <td>id</td>
      <td>made_on</td>
      <td>category</td>
      <td>description</td>
      <td>amount</td>
      <td>more </td>
    </tr>
  </thead>
  
  <tbody>
    <% @transactions.each do | transaction | %>
      <tr>
        <td> <%= transaction.id %> </td>
        <td> <%= transaction.made_on %> </td>
        <td> <%= transaction.category %> </td>
        <td> <%= transaction.description %> </td>
        <td> <%= transaction.amount %> </td>
        <td> <%= link_to "more", connection_account_transaction_path(@connection_id, @account_id, transaction.id) %>
        </td>
      </tr>
    <%  end %>
  </tbody>

</table>

app/views/transactions/show.html.erb
<div class="container">
  <%=  link_to " ⬅ back ", connection_accounts_path, class:"btn btn-primary" %> <br><br>
<% @transaction.each_pair do |key, value| %>
  
  <strong> <%= key.to_s %> </strong> <br>
  <%= value %>
  <br><br>
<% end %>
  </div>  